version: "3.9"
services:
#  api:
#    build: .
#    ports:
#      - "8000:80"
#    depends_on:
#      - db
  spa:
    container_name: "vegaForChallengeWeb"
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    volumes:
      # Mount the code in the ./ClientApp directory into the container so the any change to the code can trigger the hot reload mechanism.
      - './ClientApp:/app'
      # Add an anonymous volume for /app/node_modules so the node_modules directory would not be overwritten by the host node_modules directory
      # at runtime.
      - '/app/node_modules'
    ports:
      - '4200:4200'
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "vegaForChallengeDb"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    volumes:
      - db-volume:/var/opt/mssql
volumes:
  db-volume:
    