version: "3.9"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "vegaForChallengeDb"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    volumes:
      - db-volume:/var/opt/mssql
volumes:
  db-volume:
    